# Generated by Django 5.2.10 on 2026-02-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificate',
            name='passphrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='unsignatured_document/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='signatured_document/'),
        ),
    ]
