# Generated by Django 5.2.10 on 2026-02-06 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_users_fullname_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2027, 2, 6, 11, 12, 57, 792366, tzinfo=datetime.timezone.utc)),
        ),
    ]
