# Generated by Django 5.2.10 on 2026-02-06 11:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_apitoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2027, 2, 6, 11, 22, 1, 589967, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.organizations'),
        ),
    ]
