# Generated by Django 5.2.10 on 2026-02-06 11:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_apitoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2027, 2, 6, 11, 43, 49, 155168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Signing_challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_create', models.BooleanField(default=False)),
                ('max_content', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
