# Generated by Django 5.2.10 on 2026-02-12 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_apitoken_expires_at_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2027, 2, 12, 7, 44, 11, 282847, tzinfo=datetime.timezone.utc)),
        ),
    ]
